# Generated by Django 5.2 on 2025-04-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_alter_actor_options_alter_actor_alternate_name_and_more'),
        ('movies', '0010_delete_actor_movie_actors'),
        ('user_interactions', '0004_alter_userlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='user_lists', to='actor.actor'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='user_lists', to='movies.movie'),
        ),
    ]
