# Generated by Django 5.2 on 2025-04-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interactions', '0005_userlist_actors_alter_userlist_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='actors',
        ),
    ]
