# Generated by Django 5.2 on 2025-04-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_alter_actor_options_alter_actor_alternate_name_and_more'),
        ('user_interactions', '0006_remove_actors_from_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='user_lists', to='actor.actor'),
        ),
    ]
