# Generated by Django 5.2 on 2025-04-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('biography', models.TextField(blank=True)),
                ('alternate_name', models.CharField(blank=True, max_length=100)),
                ('introduction', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actor_images/')),
            ],
        ),
    ]
