# Generated by Django 5.2 on 2025-04-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name'], 'verbose_name': 'Diễn viên', 'verbose_name_plural': 'Diễn viên'},
        ),
        migrations.AlterField(
            model_name='actor',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tên khác'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Tiểu sử'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birthdate',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Nam'), ('Female', 'Nữ'), ('Other', 'Khác')], max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actor_images/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='Giới thiệu'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên'),
        ),
    ]
