# Generated by Django 5.2 on 2025-04-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', 'add_views_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
