# Generated by Django 5.2 on 2025-04-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_movie_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('series', 'Phim bộ'), ('single', 'Phim lẻ')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='screening_schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
