# Generated by Django 5.2 on 2025-04-18 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_movie_type_movie_screening_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('episode_number', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='episodes/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('streaming_link', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episode_thumbnails/')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.movie')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('movie', 'episode_number')},
            },
        ),
    ]
