# Generated by Django 5.2 on 2025-04-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='episode_count',
            field=models.PositiveIntegerField(blank=True, help_text='Số tập phim (chỉ áp dụng cho phim bộ)', null=True),
        ),
    ]
