# Generated by Django 5.2 on 2025-04-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_file',
            field=models.FileField(blank=True, null=True, upload_to='trailers/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
