# Generated by Django 5.2 on 2025-04-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_trailer_movie_trailer_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='streaming_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
