# Generated by Django 5.2 on 2025-04-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='actor',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
