# Generated by Django 5.2 on 2025-04-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
        ('movies', '0009_actor_alternate_name_actor_gender_actor_introduction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movies', to='actor.actor'),
        ),
    ]
